export enum CallbackId {
  SETTINGS = 'SETTINGS',
  SETUP = 'SETUP',
  MAPPING_SETUP = 'MAPPING_SETUP',
  MAPPING_UPDATE = 'MAPPING_UPDATE',
  MAPPING_CANCEL = 'MAPPING_CANCEL',
  EMPTY = 'EMPTY',
  SHOW_MAPPING = 'SHOW_MAPPING',
  RESOLVE_ERRORS = 'RESOLVE_ERRORS',
  CreateIssueFormSubmit = 'CreateIssueFormSubmit',
}
